### ISSUE TITLE
Compiling ExternalMedia using VS2017 Community

### ISSUE THREAD

**Issue by bdechesne** [modelica-3rdparty/ExternalMedia#21] opened 2019-06-04 13:40 UTC
Dear all,

I am trying to compile ExternalMedia using Visual Studio 2017 but I can't achieve to build the static library. I modified the "BuildLib-Dymola-VS2012.bat" file into "BuildLib-Dymola-VS2017.bat" and ran that file based on the info from "ExternalMedia/Projects/CompilationHowTo.txt". However, the static library is not built and copied as mentionned in that file. 

Here is a copy of the bat file I am using:

```
REM ******** set the variables ************
REM call both to ensure that one works

call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"

call BuildLib-VS "Visual Studio 15 2017"

echo "Copying files to External Media 3.2.1"
copy ExternalMediaLib.lib "..\Modelica\ExternalMedia 3.2.1\Resources\Library\win32\ExternalMediaLib.Dymola-vs2017.lib"
copy ExternalMediaLib.lib "..\Modelica\ExternalMedia 3.2.1\Resources\Library\win32\ExternalMediaLib.lib"
del ExternalMediaLib.lib
copy Sources\externalmedialib.h "..\Modelica\ExternalMedia 3.2.1\Resources\Include"
echo "All done"	
PAUSE
```

I also tried to call "vcvars32.bat" instead of "vcvarsall.bat" but without getting much better results. The static library is built and copied but the compilation of the test examples in Dymola 2019 still fails.

Did anyone already try to compile the library using VS2017 and got passed these issues?

I can of course provide more info on the errors I am getting if needed. Thanks in advance for your help. Best,

Bertrand

**Comment by dettmerramon** [comment] 2019-09-06 22:51
Hi,

The problem is not within the BuildLib-DymolaXXXX..., its in the BuildLib-VS. It pull the current github repository, which have changed since how it was a few years ago, leading to the problem of not being able to compile, even if you were to use an old version of the Visual Studio. I've managed to compile it by changing the BuildLib-VS.bat file, which i can send you next week, although i don't know if the .Lib file have been working properly because of the changes in the CoolProp repo. If i remember corretly some of the Medium of the externalmedia were working, some not.

**Comment by carowjp** [comment] 2020-07-27 19:59
Hello,

I managed to compile in MSVC also by changing the BuildLib-VS.bat file and providing the CoolProp sources, but testing in Dymola fails. Could you tell me what versions you were successful with (32 or 64 bit, which version of CoolProp etc)?

Many thanks!

**Comment by casella** [comment] 2020-07-27 20:37
The original library worked with Dymola 32 bits and with Visual Studio up to 2012. I planned to overhaul the whole thing long time ago, but I had several interruptions, and the COVID didn't help. I hope to manage this coming September.

**Comment by squoilin** [comment] 2020-08-10 06:21
In the meantime, you can try using this fork of ExternalMedia, which has some dirty fixes that allowed me to compile in VS2017:
https://github.com/squoilin/ExternalMedia

**Comment by Satinelamp** [comment] 2020-11-23 17:06
Is this issue fixed now? I still can't use the current code with Dymola 2020x and VS 2017.

**Comment by jowr** [comment] 2021-03-10 21:15
You can have alook at my latest PR. Now everything is based on CMake and should work just fine with VS 2012 through VS 2019.

**Closed** 2021-05-05 09:34 UTC
